export const SET_FAIR_DETAILS = 'SET_FAIR_DETAILS';
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const SET_SOURCE_DETAILS = 'SET_SOURCE_DETAILS';
export const SET_DESTINATION_DETAILS = 'SET_DESTINATION_DETAILS';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_DRIVER_ACTIVE_DETAILS = 'SET_DRIVER_ACTIVE_DETAILS';

